# Bot Setup
bot_mode: starters
# spin
# sweet scent
# bunny hop
# move between coords
# move until obstructed
# fishing
# starters
# rayquaza
# groudon
# kyogre
# southern island
# mew
# regi trio
# deoxys runaways
# deoxys reset
# fossil
# castform
# beldum
# johto starters
# buy premier balls
coords:
  pos1:
    - 38
    - 6
  pos2:
    - 39
    - 6
direction: Horizontal
# Vertical
# Horizontal
starter: Torchic
# Torchic
# Mudkip
# Treecko
johto_starter: Cyndaquil
# Cyndaquil
# Chikorita
# Totodile
fossil: Anorith
deoxys_puzzle_solved: false

# Autosaves
periodic_save: true
save_every_x_encounters: 1000

# Discord Webhook settings (optional)
discord_webhook_url:
# Your raw webhook URL here, if unspecified, the function's disabled.
discord_webhook_ivs: formatted 
# Choose how the IVs will display, either basic layout on one line or formatted for readability
discord_ping_mode: role
# "user" or "role", if left empty/invalid: pings are disabled.
discord_shiny_ping: 
# Discord User/Role ID to ping. Does nothing if "discord_ping_mode" isn't set. Currently supports only one at a time.

# Wild Battles
manual_catch: false
use_spore: true
catch:
- shinies
- perfect_ivs
battle_others: false
pokeball_priority:
- premier_ball
- ultra_ball
- great_ball
- poke_ball
pokeball_override: # Per-species exceptions to pokeball_priority. Falls back to pokeball_priority if it has no Pokeballs in the list
  Abra: 
  - ultra_ball
  - great_ball
cycle_lead_pokemon: true
save_game_after_catch: true
save_game_on_start: false

# Pickup
pickup: true
pickup_threshold: 3 # Number of pickup items to find before collection

# Pokemon encounter data logging (logs to stats/encounters/)
log: true

bot_instance_id: pokebot_1
# If running multiple instances of the bot, set this to the same `bot_instance_id` string at the top of pokebot.lua (use a unique string per bot instance)

# Preferences
control_map:
  a: x
  b: z
  l: w
  r: e
  up: up
  down: down
  right: right
  left: left
  select: space
  start: enter
  emu_screenshot: f12
  emu_reset_combo:
  - ctrl
  - r
banned_moves:
- None
  # 2-turn
- Bounce
- Dig
- Dive
- Fly
- Sky Attack
- Razor Wind
- Doom Desire
- Solar Beam
  # Inconsistent
- Fake Out
- False Swipe
- Nature Power
- Present
- Destiny Bond
- Wrap
- Snore
- Spit Up
- Bide
- Bind
- Counter
- Future Sight
- Mirror Coat
- Grudge
- Snatch
- Spite
- Curse
- Endeavor
- Revenge
- Assist
- Focus Punch
- Eruption
- Flail
  # Ends battle
- Roar
- Whirlwind
- Selfdestruct
- Perish Song
- Explosion
- Memento

# Cheats
do_realistic_hunt: true
